# Generated by Django 4.0.1 on 2022-01-12 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_myuser_firts_name_myuser_last_name_myuser_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='firts_name',
            new_name='first_name',
        ),
    ]
