# Generated by Django 4.0.1 on 2022-01-12 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carzoneapp', '0002_alter_profile_user'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('account', '0004_rename_firts_name_myuser_first_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyUser',
            new_name='Account',
        ),
    ]
