# Generated by Django 4.0.1 on 2022-01-12 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('carzoneapp', '0002_alter_profile_user'),
        ('account', '0005_rename_myuser_account'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Account',
            new_name='CustomUser',
        ),
    ]
