# Generated by Django 4.0.1 on 2022-01-12 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carzoneapp', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
