# Generated by Django 4.0.1 on 2022-01-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carzoneapp', '0007_banner_socialnetwork_brand_slug_car_slug_model_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
