# Generated by Django 4.0.1 on 2022-01-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carzoneapp', '0008_car_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
