# Generated by Django 4.0.1 on 2022-01-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carzoneapp', '0009_alter_car_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='social_network',
        ),
        migrations.AddField(
            model_name='team',
            name='social_network',
            field=models.ManyToManyField(related_name='team_network', to='carzoneapp.SocialNetwork'),
        ),
    ]
