# Generated by Django 4.0.1 on 2022-01-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carzoneapp', '0010_remove_team_social_network_team_social_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='image',
            field=models.FileField(null=True, upload_to='team_image'),
        ),
    ]
