# Generated by Django 4.0.1 on 2022-01-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carzoneapp', '0011_team_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='team_image'),
        ),
    ]
