# Generated by Django 4.0.1 on 2022-01-19 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carzoneapp', '0013_alter_team_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='image',
        ),
    ]
